version: "3.8"

services:
  back:
    build:
      dockerfile: "Dockerfile"
      context: "."
    volumes:
      - ./:/app:rw,cached
      - /app/node_modules
    ports:
      - 4000:4000
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecochallenge
      PGDATA: /var/lib/postgresql/data/customDataFolder
    volumes:
      - ./dbData/postgres:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ecochallenge -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy